[build]
base = "./"
command = "yarn run build"
publish = "./build"

# Keybase redirects
[[redirects]]
force = true
from = "https://jonahsnider.dev/keybase.txt"
status = 200
to = "https://jonahsnider.com/keybase.txt"

[[redirects]]
force = true
from = "https://jonahsnider.netlify.app/*"
status = 301
to = "https://jonahsnider.com/:splat"
[[redirects]]
force = true
from = "https://jonah.pw/*"
status = 301
to = "https://jonahsnider.com/:splat"
[[redirects]]
force = true
from = "https://jonahsnider.ninja/*"
status = 301
to = "https://jonahsnider.com/:splat"
[[redirects]]
force = true
from = "https://jonahsnider.dev/*"
status = 301
to = "https://github.com/jonahsnider/:splat"

# Resume Google Drive link
[[redirects]]
from = "/resume"
status = 301
to = "https://drive.google.com/file/d/11FOwQyPz1Qy8vxHyJjN_Oaxh2rHGRTzW/view?usp=sharing"

# Keybase link
[[redirects]]
from = "/keybase"
status = 301
to = "https://keybase.io/jonahsnider/"

# Email link
[[redirects]]
from = "/email"
status = 301
to = "mailto:jonah@jonahsnider.com"

# GitHub redirect for my repositories
[[redirects]]
from = "/github/*"
status = 301
to = "https://github.com/jonahsnider/:splat"

[[redirects]]
from = "/gh/*"
status = 301
to = "https://github.com/jonahsnider/:splat"

# Disable FLoC tracking https://plausible.io/blog/google-floc#how-to-opt-out-of-floc-as-a-web-developer-set-a-permissions-policy
[[headers]]
for = "/*"
[headers.values]
Permissions-Policy = "interest-cohort=()"

# Temporary fix for https://answers.netlify.com/t/web-application-manifest-mime-type/34110
[[headers]]
for = "/*.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"
